[package]
name = "test-driver"
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[dependencies]
wdrf-std.workspace = true
wdrf = { path = "../wdrf", version = "0.1.0", features = ["minifilter"] }
anyhow.workspace = true
wdk.workspace = true
wdk-alloc.workspace = true
wdk-sys.workspace = true
widestring.workspace = true
maple.workspace = true
nt-string.workspace = true

[build-dependencies]
wdk-build.workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.wdk]
