[package]
name = "test-driver"
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[dependencies]
wdrf-std.workspace = true
wdrf.workspace = true
anyhow.workspace = true
wdk.workspace = true
wdk-alloc.workspace = true
wdk-sys.workspace = true
wchar.workspace = true

[build-dependencies]
wdk-build.workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.wdk]

[profile.dev]
panic = "abort"
lto = true      # optional setting to enable Link Time Optimizations

[profile.release]
panic = "abort"
lto = true      # optional setting to enable Link Time Optimizations
