[package]
name = "wdrf-proc-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
deluxe = "0.5.0"
proc-macro2 = "1.0.79"
quote = { version = "1.0.35", features = [] }
syn = { version = "2.0.58", features = ["full", "extra-traits"] }
windows-sys.workspace = true
