[package]
name = "wdrf-macros"
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[dependencies]
windows-sys.workspace = true
wdrf-proc-macros = { path = "./wdrf-proc-macros", version = "0.1.0" }
