[package]
name = "maple"
version = "0.1.0"
edition.workspace = true
repository.workspace = true

[profile.dev]
panic = "abort"
lto = true

[profile.release]
panic = "abort"
lto = true

[dependencies]
anyhow.workspace = true

[features]
default = ["debug"]
debug = []
